stages:
  - dependencies
  - build
  - deploy

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  DOCKER_REGISTRY: "docker.miracum.org"
  IMAGE_PATH: "r_package_ci"
  CI_IMAGE_NAME: "${DOCKER_REGISTRY}/${IMAGE_PATH}/${CI_PROJECT_NAME}_base_image"
  CI_IMAGE_TAG: "0.0.2"
  R_PKG_NAME: "tromics"

.docker_registry:
  before_script:
    - echo ${REGISTRY_PASSWORD} | docker login -u ${REGISTRY_USERNAME} ${DOCKER_REGISTRY} --password-stdin
  after_script:
    - docker logout ${DOCKER_REGISTRY}

default:
  image: ${CI_IMAGE_NAME}:${CI_IMAGE_TAG}
  before_script:
    - echo "options('repos' = 'https://ftp.fau.de/cran/')" >> /usr/local/lib/R/etc/Rprofile.site
    - mkdir -p ci

# https://gitlab.com/gitlab-org/gitlab/issues/22801
build_base_image:
  stage: dependencies
  image: docker:stable
  extends: .docker_registry
  script:
    - cd .. && docker build --build-arg PKG_NAME=${R_PKG_NAME} -t ${CI_IMAGE_NAME}:${CI_IMAGE_TAG} -f ${CI_PROJECT_NAME}/ci/Dockerfile .
    - docker push ${CI_IMAGE_NAME}
  only:
    # build only when there are changes in dependencies
    changes:
      - "data-raw/devstuffs.R"
      - "ci/Dockerfile"
    refs:
      - master
      - development
  except:
    refs:
      - tags

check:
  stage: build
  allow_failure: true # necessary when having development-packages (in remotes-section of DESCRIPTION)
  script:
    - R -e "devtools::install_dev_deps(pkg = '.', upgrade = 'always')"
    - R -e "devtools::check(pkg = '.', args = c('--no-tests', '--no-vignettes'), build_args = c('--no-build-vignettes'), check_dir = '${CI_PROJECT_DIR}/ci')"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/ci/*.Rcheck"
    when: on_failure # upload check artifacts when job fails!
    expire_in: 1 week
  except:
    refs:
      - tags
  only:
    refs:
      - master
      - development

create_manual:
  stage: build
  allow_failure: true
  script:
    - R -e "devtools::install_deps(pkg = '.', upgrade = 'always')"
    - R -e "devtools::build_manual(pkg = '.', path = '${CI_PROJECT_DIR}/ci')"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/ci/*.pdf"
    expire_in: 1 week
  except:
    refs:
      - tags
  only:
    refs:
      - master

build_source_and_binary:
  stage: build
  script:
    - R -e "devtools::install_deps(pkg = '.', upgrade = 'always')"
    - R -e "devtools::build(pkg = '.', path = '${CI_PROJECT_DIR}/ci', binary = FALSE, vignettes = FALSE)"
    - R -e "devtools::build(pkg = '.', path = '${CI_PROJECT_DIR}/ci', binary = TRUE, vignettes = FALSE)"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/ci/*.tar.gz"
    expire_in: 1 week
  except:
    refs:
      - tags
  only:
    refs:
      - master

testing:
  stage: build
  allow_failure: true
  when: on_success
  script:
    - R -e "devtools::install_dev_deps(pkg = '.', upgrade = 'always')" # we only need dev_deps for the vignette and testing
    - R -e "devtools::test(pkg = '.')"
  except:
    refs:
      - tags
  only:
    refs:
      - master
      - development

# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

install:
  stage: deploy
  script:
    - R -e "devtools::install_deps(pkg = '.', upgrade = 'always')" # we only need dev_deps for the vignette and testing
    - R -e "devtools::install(pkg = '.', upgrade = 'alway')"
  except:
    refs:
      - tags
  only:
    refs:
      - master
